#!/usr/bin/env python3
"""
CCTV Telemetry Ingestion & In-Memory Storage
Purplle Store Intelligence Challenge

This module provides thread-safe, in-memory event storage, loads raw JSON logs
generated by the pipelines, filters duplicate entries, and validates schemas using Pydantic.
"""

import os
import sys
import json
import logging
import threading
import argparse
from typing import List, Dict, Set, Any, Optional, Tuple

# Setup import paths to allow executing this file directly
try:
    from app.models import CCTVEventPayload, CCTVBatchEvents
except ImportError:
    try:
        from models import CCTVEventPayload, CCTVBatchEvents
    except ImportError:
        sys.path.append(os.path.dirname(os.path.abspath(__file__)))
        from models import CCTVEventPayload, CCTVBatchEvents

# ==============================================================================
# Logging Configuration
# ==============================================================================
def setup_logger(log_level: int = logging.INFO) -> logging.Logger:
    """
    Sets up a standardized logger for the ingestion engine.
    """
    logger = logging.getLogger("CCTV_Ingestion")
    logger.setLevel(log_level)
    
    if not logger.handlers:
        handler = logging.StreamHandler(sys.stdout)
        formatter = logging.Formatter(
            '[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )
        handler.setFormatter(formatter)
        logger.addHandler(handler)
        
    return logger

logger = setup_logger()

# ==============================================================================
# In-Memory Event Store (Thread-Safe)
# ==============================================================================
class InMemoryEventStore:
    """
    A thread-safe in-memory database to store, retrieve, and filter
    validated store telemetry events.
    """
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._events: List[CCTVEventPayload] = []
        
        # Deduplication index set: (camera_id, track_id, timestamp, event_type)
        self._dedup_index: Set[Tuple[str, int, float, str]] = set()

    def add_event(self, event: CCTVEventPayload) -> bool:
        """
        Validates and adds an event if it is unique.
        Returns True if successfully added, False if duplicate.
        """
        # Generate unique event signature
        signature = (
            event.camera_id,
            event.track_id,
            round(event.timestamp, 2),  # Round to avoid float precision discrepancies
            event.event_type
        )
        
        with self._lock:
            if signature in self._dedup_index:
                return False
                
            self._events.append(event)
            self._dedup_index.add(signature)
            return True

    def get_all_events(self) -> List[CCTVEventPayload]:
        """
        Returns a copy of all registered events.
        """
        with self._lock:
            return list(self._events)

    def get_events_by_camera(self, camera_id: str) -> List[CCTVEventPayload]:
        """
        Filters events by camera source.
        """
        with self._lock:
            return [e for e in self._events if e.camera_id == camera_id]

    def get_events_by_track(self, track_id: int) -> List[CCTVEventPayload]:
        """
        Filters events by customer tracking ID.
        """
        with self._lock:
            return [e for e in self._events if e.track_id == track_id]

    def clear(self) -> None:
        """
        Clears all stored events and the deduplication index.
        """
        with self._lock:
            self._events.clear()
            self._dedup_index.clear()
            logger.info("In-memory event store cleared.")

    @property
    def count(self) -> int:
        """
        Returns total number of events in memory.
        """
        with self._lock:
            return len(self._events)


# Global Singleton Instance for API & Dashboard usage
store = InMemoryEventStore()

# ==============================================================================
# Ingestion Utility & Helper Functions
# ==============================================================================
def parse_and_validate_raw_event(event_dict: Dict[str, Any]) -> Optional[CCTVEventPayload]:
    """
    Validates a raw dictionary against the CCTVEventPayload Pydantic schema.
    Returns the parsed Pydantic object if valid, None otherwise.
    """
    try:
        # Standardize dictionary keys to match schema naming if needed
        # (e.g. if tracking output has slightly different format)
        if "track_id" not in event_dict and "id" in event_dict:
            event_dict["track_id"] = event_dict["id"]
            
        validated = CCTVEventPayload.model_validate(event_dict)
        return validated
    except Exception as e:
        logger.debug(f"Event failed schema validation. Content: {event_dict}. Error: {e}")
        return None


def ingest_batch_payload(batch: CCTVBatchEvents) -> int:
    """
    Ingests a validated batch Pydantic payload directly from REST API posts.
    Returns the count of successfully ingested non-duplicate events.
    """
    added_count = 0
    duplicate_count = 0
    
    for event in batch.events:
        if store.add_event(event):
            added_count += 1
        else:
            duplicate_count += 1
            
    if duplicate_count > 0:
        logger.debug(f"Ignored {duplicate_count} duplicate events in batch.")
        
    return added_count


def ingest_json_file(file_path: str, camera_id_override: Optional[str] = None) -> int:
    """
    Loads, parses, validates, deduplicates, and ingests events from a JSON log file.
    Supports both event list outputs and frame-by-frame tracker output structures.
    """
    if not os.path.exists(file_path):
        logger.error(f"Ingestion failed. Target file not found at: {file_path}")
        return 0
        
    logger.info(f"Loading telemetry file for ingestion: {file_path}")
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        logger.error(f"Failed to read or parse JSON file. Error: {e}")
        return 0
        
    raw_events: List[Dict[str, Any]] = []
    
    # Identify video pipeline log format dynamically:
    # 1. Format A (Event Emitter output): A JSON array of event objects
    if isinstance(data, list):
        raw_events = data
        
    # 2. Format B (Event Emitter wrapped dict): Dictionary containing "frames" or "events"
    elif isinstance(data, dict):
        if "events" in data and isinstance(data["events"], list):
            raw_events = data["events"]
        elif "frames" in data and isinstance(data["frames"], list):
            # Convert raw frame detections (pipeline tracking logs) into standard update events
            inferred_camera = camera_id_override or "camera_stream"
            
            # If metadata includes a camera field, use it
            if "metadata" in data and isinstance(data["metadata"], dict):
                inferred_camera = data["metadata"].get("video_source", inferred_camera)
                # Clean path naming if any
                inferred_camera = os.path.basename(inferred_camera).split('.')[0]
                
            for frame in data["frames"]:
                frame_idx = frame.get("frame_index", 0)
                timestamp = frame.get("timestamp_ms", float(frame_idx * 40)) # Default 25fps estimate
                
                # Check for active detections list
                detections = frame.get("detections", [])
                for det in detections:
                    # Elevate detections to standard updates
                    raw_events.append({
                        "timestamp": timestamp,
                        "camera_id": inferred_camera,
                        "track_id": det.get("track_id", 0),
                        "bbox": det.get("bbox", [0, 0, 0, 0]),
                        "confidence": det.get("confidence", 1.0),
                        "event_type": "update"
                    })
        else:
            # Single event dict
            raw_events = [data]
            
    logger.info(f"Loaded {len(raw_events)} raw telemetry points. Validating and deduplicating...")
    
    added_count = 0
    failed_validation = 0
    duplicates = 0
    
    for idx, raw in enumerate(raw_events):
        # Override camera ID if requested
        if camera_id_override:
            raw["camera_id"] = camera_id_override
            
        validated = parse_and_validate_raw_event(raw)
        if validated is not None:
            if store.add_event(validated):
                added_count += 1
            else:
                duplicates += 1
        else:
            failed_validation += 1
            
    logger.info(
        f"Ingestion complete | "
        f"Successfully Added: {added_count} | "
        f"Skipped Duplicates: {duplicates} | "
        f"Failed Validation: {failed_validation}"
    )
    
    return added_count


# ==============================================================================
# CLI Testing Interface
# ==============================================================================
def main() -> None:
    """
    Diagnostic CLI interface to perform standalone ingestion tests.
    """
    parser = argparse.ArgumentParser(
        description="CCTV Analytics Ingestion Engine Diagnostics"
    )
    parser.add_argument(
        "--file_path",
        type=str,
        help="Path to an events.json or tracking_events.json file to ingest."
    )
    parser.add_argument(
        "--camera_id",
        type=str,
        help="Optional camera identifier override for ingestion."
    )
    
    args = parser.parse_args()
    
    if args.file_path:
        count = ingest_json_file(args.file_path, camera_id_override=args.camera_id)
        print(f"\n--- Diagnostic Ingestion In-Memory Summary ---")
        print(f"Total Unique Events Registered in Cache: {store.count}")
        
        # Display sample entry
        events = store.get_all_events()
        if events:
            print(f"Sample Ingested Event Payload:")
            print(json.dumps(events[0].model_dump(), indent=4))
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
